USE Mydatabase;
CREATE TABLE EMPLOYEE
(E_ID int(5),
E_Name varchar(25),
E_Dept varchar(25));
DESCRIBE EMPLOYEE;
SELECT * FROM EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(1001,'KUNAL','DEVELOPER');
INSERT INTO EMPLOYEE VALUES(1002,'MANOJ','TESTING');
INSERT INTO EMPLOYEE VALUES(1003,'SANAYA','RESEARCH & DEVELOPMENT');
INSERT INTO EMPLOYEE VALUES(1004,'MRUNAL','HR');
INSERT INTO EMPLOYEE VALUES(1005,'KUMUD','RESEARCH & DEVELOPMENT');
INSERT INTO EMPLOYEE VALUES(1006,'SITU','TESTING');
INSERT INTO EMPLOYEE VALUES(1007,'ROSE','HR');
INSERT INTO EMPLOYEE VALUES(1009,'AKSHYA','DEVELOPER');
SELECT * FROM EMPLOYEE;
SELECT E_Name EName,E_ID EID FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE E_ID = 1005;

